# Generated by Django 2.1 on 2018-08-09 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id_dieta', models.AutoField(primary_key=True, serialize=False)),
                ('inicio', models.DateField()),
                ('final', models.DateField()),
                ('peso_ideal', models.FloatField()),
                ('altura', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Peso',
            fields=[
                ('id_peso', models.AutoField(primary_key=True, serialize=False)),
                ('peso', models.FloatField()),
                ('data_pesagem', models.DateField()),
                ('dieta_peso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dieta.Info')),
            ],
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id_refeicao', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('CAFE_MANHA', 'Café da Manhã'), ('LANCHE', 'Lanche'), ('ALMOCO', 'Almoço'), ('JANTAR', 'Jantar'), ('CEIA', 'Ceia')], default='CAFE_MANHA', max_length=10)),
                ('horario', models.TimeField()),
                ('descricao', models.TextField()),
                ('refeicao_dieta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dieta.Info')),
            ],
        ),
    ]
