# Generated by Django 2.1 on 2018-08-10 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id_dieta', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('peso_ideal', models.FloatField()),
                ('altura', models.FloatField()),
                ('usuario', models.ForeignKey(default=0, editable=0, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Peso',
            fields=[
                ('id_peso', models.AutoField(primary_key=True, serialize=False)),
                ('peso', models.FloatField()),
                ('data_pesagem', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id_refeicao', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('CAFE_MANHA', 'Café da Manhã'), ('LANCHE', 'Lanche'), ('ALMOCO', 'Almoço'), ('JANTAR', 'Jantar'), ('CEIA', 'Ceia')], default='CAFE_MANHA', max_length=10)),
                ('horario', models.TimeField()),
                ('descricao', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
